### PR TITLE
Document how to release both an sdist and wheel distribution

### LINKED ISSUE #177: Provide wheel distribution on PyPI
Hi!

Please could this package also by made available as a wheel on PyPI?
https://pypi.python.org/pypi/djangorestframework-filters

Wheels have the following advantages:
* Faster installation time
* Allows the wheel cache to work even when using the new pip hash-checking mode
* Allows tools to statically inspect the package metadata without having to execute untrusted code.
* ...and more - see: http://pythonwheels.com

This package is pure Python and supports both Python 2 and 3, so can be distributed as a "universal wheel":
https://packaging.python.org/tutorials/distributing-packages/#wheels

To save having to pass `--universal` to `setup.py` each time, the pref can be saved in `setup.cfg`:

```
[bdist_wheel]
universal=1
```

The Python packaging guide recommends using [Twine](https://github.com/pypa/twine) to upload packages:
https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

So with the `setup.cfg` as above, the steps for building/uploading a new release are then:

```bash
$ pip install -U twine setuptools wheel
$ rm -rf dist/ build/
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

The PyPI package listing will then display two entries for the new release, one with type "Source" and the other "Python Wheel".

Many thanks :-)

### PR DESCRIPTION
**Pull request by edmorley**
Fixes #177.

### CODE REVIEW

**Comment by edmorley** [comment]
@philipn Hi! I don't suppose you've had a chance to look at this? :-)

**Comment by edmorley** [comment]
Or @rpkilby? :-)

**Comment by rpkilby** [comment]
Ultimately, @philipn is in control of the release process, so this is up to him. That said, I definitely think it's a good idea.

**Comment by philipn** [comment]
Thanks @edmorley!

**Pull request merged**
