### PR TITLE
Restructure tests

### PR DESCRIPTION
**Pull request by rpkilby**
- breaks apart tests module into package
- simplifies test data definitions
- removes 1s timing delay
- tests are no longer distributed with the package on pypi

### CODE REVIEW

**Comment by philipn** [comment]
This looks great, but RE: "tests are no longer distributed with the package on pypi": Most people don't run their dependencies' tests, some people might want to.  I noticed that DRF doesn't distribute their tests.  Is there a convention here?

**Comment by rpkilby** [comment]
Hm, I think the general consensus is to exclude tests from the distributed package. Basically,
- Most users don't care about running their dependencies' tests continuously. They rely on code coverage/other metrics, and community reputation/popularity. Essentially, a one time valuation that the code meets their standards.
- For the users that do want to run the tests, this often requires additional test dependencies and setup anyway, so they would need to add a step to their build process.

**Comment by rpkilby** [comment]
@philipn - Did you have a chance to think about this? After looking at a number of other packages, I'm still of the opinion to not include tests, but it's not a very important issue to me.

**Comment by philipn** [comment]
Sweet, looks great!

**Pull request merged**
