### PR TITLE
__in filter

### PR DESCRIPTION
**Pull request by manuelnaranjo**
Hello guys,

I created a rather simple filter for __in filters, it now lets me do things like:

       <server>robots/rest/products/?pk__in=1,5,2

I may have missed some cases, added unittests to make sure nothing got broken and that it works reasonably well.

### CODE REVIEW

**Comment by karmux** [comment]
If I don't use __in= filter then I always get this error:
```
AttributeError at /foo/
'NoneType' object has no attribute 'split'
Request Method:	GET
Request URL:	http://my-host/foo/
Django Version:	1.8.2
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'split'
Exception Location:	/usr/local/lib/python3.4/dist-packages/rest_framework_filters/fields.py in clean, line 6
Python Executable:	/usr/bin/python3
Python Version:	3.4.2
Python Path:	
['/project',
 '/usr/local/lib/python3.4/dist-packages/pip-7.0.1-py3.4.egg',
 '/src/pika',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']
Server time:	Thu, 11 Jun 2015 12:33:36 +0000
```
__in= filter itself seems to work.

**Comment by philipn** [comment]
@manuelnaranjo, could you add a test case for @karmux's error above?

**Comment by manuelnaranjo** [comment]
sure I'll put this on my TODO list

**Comment by manuelnaranjo** [comment]
@karmux would you mind telling me your test case?

**Comment by karmux** [comment]
@manuelnaranjo , I retested and now it works. Thanks! I'd love to see it merged.

**Comment by philipn** [comment]
Thank you two so much here for the great work!  I'm merging this now.  We may want a bit more documentation about this on the homepage after this.

**Comment by manuelnaranjo** [comment]
Are we getting any updated package with this feature?

**Comment by philipn** [comment]
@manuelnaranjo Thanks for the poke.  Just pushed 0.3.1 to PyPI.

**Comment by manuelnaranjo** [comment]
cool thanks

**Comment by AndySun25** [comment]
Is there any chance to allow for __in filtering for non-integer fields as well?

**Comment by manuelnaranjo** [comment]
@AndySun25 I though about that as well, problem is how you split non integer fields. In a string a coma could be a valid piece

**Comment by AndySun25** [comment]
You could have it as a setting in django configuration.

**Comment by manuelnaranjo** [comment]
mhh... what about two new options to the __in configuration filter? FieldType and separator. What do others think about this? I haven't looked at how to implement it yet, but I think I could

**Pull request merged**
