### PR TITLE
use django-filter version that supports python 2.7 for v0.10.x

### PR DESCRIPTION
**Pull request by kwigley**
For issue #253

Might be nice to have a v1.10.3 for this and have a proper branch for 0.10.x.

### CODE REVIEW

**Comment by kwigley** [comment]
Wasn't sure where to point this!

**Comment by rpkilby** [comment]
Thanks for the patch, but I don't think it's worth the effort to ship a 0.10.3 just to bound the python versions. This is more appropriately solved at a user/application level by version locking your requirements file. I would recommend using something like `pip-tools`.

**Comment by kwigley** [comment]
Thanks @rpkilby! Agree that's the best practice solution and the solution I am using, new users may have in issue on a fresh `djangorestframework-filters` install.

**Comment by ses4j** [comment]
@rpkilby I would like to second @kwigley 's suggestion for a Py 2.7 branch of this library.  

This issue is going to affect anyone trying to use `django-rest-framework-filters` with Python 2.x, which I have to imagine is a lot of people, and the fix is not at all clear when it first happens to you.  Switching a large legacy project from Py 2 to 3 may be a good idea, but it's not one that needs to or ought to be driven by this library.

**Comment by rpkilby** [comment]
Hi @ses4j. The issue is that django-filter 2.x is Python 3 only, and the setup.py doesn't include the necessary `python_requires` marker. I've created https://github.com/carltongibson/django-filter/pull/953 to address this. The upcoming 1.0 release of this package will also include the marker, which should cause installation to fail for users working with Python 2. 

Users still on Python 2 should stick with django-filter `v1.1.0` and django-rest-framework-filters `v0.10.2`.

**Comment by rpkilby** [comment]
Hi all, I went ahead and created a `0.10.x` branch that set the django-filter version to 1.x-compatible releases. @philipn should be able to create a post-release at some point.

**Pull request closed without merging**
